on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  report: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set virtual environment and dependencies
        run: |
          uv sync
          echo $(uv --version)
          uv run python -m playwright install chromium

      - name: Set up Gemini API key
        run: | 
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV

      - name: Fetch news articles
        run: |
          echo "Fetching news articles..."
          uv run python -m src.g_news_summarization.get_data

      - name: Generate summaries
        run: |
          echo "Generating summaries..."
          uv run python -m src.g_news_summarization.generate_summary
          echo "Summaries generated successfully."

      - name: Add db file to the Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: daily-summary
          files: data/articles_data.db

      - name: Create a vector database
        run: |
          echo "Creating vector database..."
          uv run python -m src.g_news_summarization.generate_embeddings

      - name: Zip the chroma vector database
        run: tar -czf vector_db.tar.gz -C data chroma_db

      - name: Upload vector database to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: daily-summary
          files: vector_db.tar.gz



        